name: Build and publish a Docker images

on:
  push:
    branches:
      - main
   workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Publish Docker Images
        run: |
          for dockerfile in $(find docker -type f -name Dockerfile); do
            # Get the directory containing the Dockerfile
            dir=$(dirname $dockerfile)

            # Extract the image name from the directory structure
            image_name="ghcr.io/${{ github.repository_owner }}/$(basename $dir)"

            # Build and push the Docker image
            docker buildx build -t $image_name $dir
            docker push $image_name
          done